shell: zsh
region: us-east-1
dotfiles: https://github.com/johnemau/workspace-dotfiles
editor: cursor
vscode-template: "dd-source"
vscode-extensions:
- "anthropic.claude-code"
- "openai.chatgpt"
- "ms-azuretools.vscode-docker"
- "bazelbuild.vscode-bazel"
- "datadog.datadog-vscode"
- "stackBuild.bazel-stack-vscode"
- "eamodio.gitlens"
- "redhat.vscode-yaml"
- "golang.go"
- "ms-python.python"
- "ms-python.vscode-pylance"
- "timonwong.shellcheck"
- "tamasfe.even-better-toml"
- "streetsidesoftware.code-spell-checker"
- "hoovercj.vscode-power-mode"
- "activitywatch.aw-watcher-vscode"
